### ISSUE TITLE
Free books download after loading kill the program

### ISSUE THREAD

**Issue by robertlc04** [Librum-Reader/Librum#58]
**Describe the bug**
After load the free books download the programs kill. Inclusive with verbose don't launch any error

[Video of the bug](https://drive.google.com/file/d/1HUUqwaE8NZ_Gp9oUhArn2Y0sbiLvx0Xa/view?usp=sharing)

PC info:
OS: Fedora Linux 38 (Sway) x86_64
Host: VivoBook_ASUSLaptop X515JA_X515JA 1.0
Kernel: 6.5.5-200.fc38.x86_64
Shell: zsh 5.9
Resolution: 1920x1080
DE: Hyprland
Terminal: WezTerm
CPU: Intel i3-1005G1 (4) @ 3.400GHz
GPU: Intel Iris Plus Graphics G1
Memory: 3916MiB / 11688MiB

Package info:
```
flatpak info com.librumreader.librum
          ID: com.librumreader.librum
         Ref: app/com.librumreader.librum/x86_64/stable
        Arch: x86_64
      Branch: stable
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 61.6 MB
     Runtime: org.kde.Platform/x86_64/6.5
         Sdk: org.kde.Sdk/x86_64/6.5
```

Verbose info:
```
flatpak run --devel -v com.librumreader.librum
F: No installations directory in /etc/flatpak/installations.d. Skipping
F: Opening system flatpak installation at path /var/lib/flatpak
F: Opening user flatpak installation at path /home/robert/.local/share/flatpak
F: Opening user flatpak installation at path /home/robert/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: Skipping parental controls check for app/com.librumreader.librum/x86_64/stable since parental controls are disabled globally
F: Opening user flatpak installation at path /home/robert/.local/share/flatpak
F: Opening system flatpak installation at path /var/lib/flatpak
F: /var/lib/flatpak/runtime/org.kde.Sdk/x86_64/6.5/1b1663b06f7fb46de8fb88f943da66b207492ed9935b21b4cc011443263379f0/files/lib32 does not exist
F: Cleaning up unused container id 1556101972
F: Cleaning up per-app-ID state for com.librumreader.librum
F: Allocated instance id 1939827902
F: Add defaults in dir /com/librumreader/librum/
F: Add locks in dir /com/librumreader/librum/
F: Allowing dri access
F: Allowing homedir access
F: Allowing wayland access
```

PD: i tray to debug more but don't have a "log" :')

**Comment by 3036662** [comment]
I have the same. Segmentation fault...(

**Comment by DavidLazarescu** [comment]
Hey, this is a known issue and will be fixed in the next update. It is due to a jpeg library version mismatch.

**Comment by DavidLazarescu** [comment]
We are waiting for flatpak to make Qt 6.6 available since this is supposed to fix the jpeg library version missmatch

**Comment by 3036662** [comment]
I thought the bug is fixed, because for now in version 0.10.0 I have no crash, everything works fine. But I use all system libraries when build Mupdf . I build client with qt6.4 , but I don't think it really important.

**Comment by DavidLazarescu** [comment]
So it works fine for your self-build version? What about the one you get via flatpak?, the issue still exists there afaik.

**Comment by 3036662** [comment]
Sorry i didn't even try to get it with flatpack)  I had a program crash (by segmentation fault)  on v0.9.2 self-builded, but now with new release - everything is fine with free books.

**Comment by DavidLazarescu** [comment]
Ah I understand. Yeah, self-building is a different environment than flatpak. Selfbuilding it works fine for me as well, but with flatpak, Qt gets confused about what jpeg library to choose, since one of Librum's dependencies (mupdf) comes with a different version of libjpeg

**Comment by tbabej** [comment]
It crashes for me on a self-built version of Librum as well, with the following jpeg libraries reported by the coredump:
>  Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-3.fc39.x86_64
>  Module libqjpeg.so from rpm qt6-qtbase-6.6.0-2.fc39.x86_64

The stacktrace itself is not very informative:
>    Stack trace of thread 945247:
>    #0  0x00007fc04cf40d8e ____longjmp_chk (libc.so.6 + 0x122d8e)
>    #1  0x69746ba155eccb48 n/a (n/a + 0x0)

**Comment by DavidLazarescu** [comment]
> It crashes for me on a self-built version of Librum as well, with the following jpeg libraries reported by the coredump:
> 
> > Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-3.fc39.x86_64
> > Module libqjpeg.so from rpm qt6-qtbase-6.6.0-2.fc39.x86_64
> 
> The stacktrace itself is not very informative:
> 
> > Stack trace of thread 945247:
> > #0  0x00007fc04cf40d8e ____longjmp_chk (libc.so.6 + 0x122d8e)
> > #1  0x69746ba155eccb48 n/a (n/a + 0x0)
> 
> This is using current main, built from [ff08ad2](https://github.com/Librum-Reader/Librum/commit/ff08ad20fe8f18c8274e5b6af7dd92ef48df4144)

Thanks for confirming it. Its the same I get.

The problem arises due to the fact that one of our dependencies builds libjpeg from source (mupdf) and the linker gets confused on which version to use, the self-built one or the one provided by the system.

If the error persists even though you built it yourself with Qt 6.6 it most probably isn't flatpak specific. 
I'll look for a solution to this.

**Comment by 3036662** [comment]
> our dependencies builds libjpeg

Maybe it will help somebody... 
I'll give a tip - when i force mupdf to use linux system libraries including libjpeg, everything works fine.
More details: extract , rapidfuzz and mujs are builded from source, other libraries are skipped, system libs are used.

**Comment by DavidLazarescu** [comment]
> > our dependencies builds libjpeg
> 
> Maybe it will help somebody... I'll give a tip - when i force mupdf to use linux system libraries including libjpeg, everything works fine. More details: extract , rapidfuzz and mujs are builded from source, other libraries are skipped, system libs are used.

How do you force mupdf to use libjpeg and not build it from source?

**Comment by 3036662** [comment]
> How do you force mupdf to use libjpeg and not build it from source?

I patch libs/mupdf/scripts/wrap/__main__.py.

```
-    make_args = ' HAVE_GLUT=no HAVE_PTHREAD=yes verbose=yes'
+    make_args = '  USE_SYSTEM_LIBS=yes USE_SYSTEM_LIBJPEG=yes USE_SYSTEM_OPENJPEG=yes USE_SYSTEM_GUMBO=yes USE_SYSTEM_MUJS=no USE_SYSTEM_FREETYPE=yes USE_SYSTEM_HARFBUZZ=yes USE_SYSTEM_ZLIB=yes  USE_SYSTEM_JBIG2DEC=yes  USE_SYSTEM_LCMS2=yes USE_SYSTEM_LEPTONICA=yes USE_SYSTEM_TESSERACT=yes USE_SYSTEM_CURL=yes USE_SYSTEM_GLUT=yes HAVE_GLUT=no HAVE_PTHREAD=yes verbose=yes  '
```

**Comment by DavidLazarescu** [comment]
> It crashes for me on a self-built version of Librum as well, with the following jpeg libraries reported by the coredump:
> 
> > Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-3.fc39.x86_64
> > Module libqjpeg.so from rpm qt6-qtbase-6.6.0-2.fc39.x86_64
> 
> The stacktrace itself is not very informative:
> 
> > Stack trace of thread 945247:
> > #0  0x00007fc04cf40d8e ____longjmp_chk (libc.so.6 + 0x122d8e)
> > #1  0x69746ba155eccb48 n/a (n/a + 0x0)
> 
> This is using current main, built from [ff08ad2](https://github.com/Librum-Reader/Librum/commit/ff08ad20fe8f18c8274e5b6af7dd92ef48df4144)

Could you try if adding:
```
set(ENV{USE_SYSTEM_LIBJPEG} yes)
```
To line 102 of src/application/CMakeLists.txt fixes your problem?

**Comment by tbabej** [comment]
> > It crashes for me on a self-built version of Librum as well, with the following jpeg libraries reported by the coredump:
> > > Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-3.fc39.x86_64
> > > Module libqjpeg.so from rpm qt6-qtbase-6.6.0-2.fc39.x86_64
> > 
> > 
> > The stacktrace itself is not very informative:
> > > Stack trace of thread 945247:
> > > #0  0x00007fc04cf40d8e ____longjmp_chk (libc.so.6 + 0x122d8e)
> > > #1  0x69746ba155eccb48 n/a (n/a + 0x0)
> > 
> > 
> > This is using current main, built from [ff08ad2](https://github.com/Librum-Reader/Librum/commit/ff08ad20fe8f18c8274e5b6af7dd92ef48df4144)
> 
> Could you try if adding:
> 
> ```
> set(ENV{USE_SYSTEM_LIBJPEG} yes)
> ```
> 
> To line 102 of src/application/CMakeLists.txt fixes your problem?

I tried the suggestion above as well as the mupdf patch above that, none of those helped on my end.

**Comment by DavidLazarescu** [comment]
> > > It crashes for me on a self-built version of Librum as well, with the following jpeg libraries reported by the coredump:
> > > > Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-3.fc39.x86_64
> > > > Module libqjpeg.so from rpm qt6-qtbase-6.6.0-2.fc39.x86_64
> > > 
> > > 
> > > The stacktrace itself is not very informative:
> > > > Stack trace of thread 945247:
> > > > #0  0x00007fc04cf40d8e ____longjmp_chk (libc.so.6 + 0x122d8e)
> > > > #1  0x69746ba155eccb48 n/a (n/a + 0x0)
> > > 
> > > 
> > > This is using current main, built from [ff08ad2](https://github.com/Librum-Reader/Librum/commit/ff08ad20fe8f18c8274e5b6af7dd92ef48df4144)
> > 
> > 
> > Could you try if adding:
> > ```
> > set(ENV{USE_SYSTEM_LIBJPEG} yes)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To line 102 of src/application/CMakeLists.txt fixes your problem?
> 
> I tried the suggestion above as well as the mupdf patch above that, none of those helped on my end.

Have you deleted the /libs/mupdf/build folder before rebuilding with the new environment variable?

**Comment by DavidLazarescu** [comment]
> > > It crashes for me on a self-built version of Librum as well, with the following jpeg libraries reported by the coredump:
> > > > Module libjpeg.so.62 from rpm libjpeg-turbo-2.1.4-3.fc39.x86_64
> > > > Module libqjpeg.so from rpm qt6-qtbase-6.6.0-2.fc39.x86_64
> > > 
> > > 
> > > The stacktrace itself is not very informative:
> > > > Stack trace of thread 945247:
> > > > #0  0x00007fc04cf40d8e ____longjmp_chk (libc.so.6 + 0x122d8e)
> > > > #1  0x69746ba155eccb48 n/a (n/a + 0x0)
> > > 
> > > 
> > > This is using current main, built from [ff08ad2](https://github.com/Librum-Reader/Librum/commit/ff08ad20fe8f18c8274e5b6af7dd92ef48df4144)
> > 
> > 
> > Could you try if adding:
> > ```
> > set(ENV{USE_SYSTEM_LIBJPEG} yes)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > To line 102 of src/application/CMakeLists.txt fixes your problem?
> 
> I tried the suggestion above as well as the mupdf patch above that, none of those helped on my end.

Ok, this was a mistake on my end. Setting environment variables as I did before seems to only set them for the cmake configuration step, not for the build step. My latest commit should now finally fix the issue (at least it seems to do so on my PC).

It would be great if someone could confirm this, since I will publish a new version tomorrow and it would be great to know if this fully fixes the error for everyone.

**Comment by 3036662** [comment]
If no, just let me know, I'll help with this if you wish

**Comment by DavidLazarescu** [comment]
The latest release of Librum fixed this.
